#ifndef CONFIG_H
#define CONFIG_H

#define MAX_GENERATIONS 2000
#define ISLANDS 384

#define WARPS_PER_ISLAND 16
#define ISLAND_POP_SIZE (WARPS_PER_ISLAND * 32)
#define POP_SIZE (ISLANDS * ISLAND_POP_SIZE)

#define TOURNAMENT_SIZE (int)(ISLAND_POP_SIZE * 0.20)

#define MUTATION_RATE 0.050
#define MUTATION_GROWTH 0.00050
#define MUTATION_THRESHOLD 0.150

#define MIGRATION_FREQUENCY 150
#define MIGRATION_SIZE (int)(ISLAND_POP_SIZE * 0.02)

#endif